local H = require("helper")
local Prompts = require("kocatchup_prompts")

describe("kocatchup_prompts", function()
    before_each(function() H.reset() end)

    local meta = { title = "Dune", authors = "Frank Herbert", chapter = "Chapter 12" }

    it("includes book metadata and the extracted text", function()
        local p = Prompts.build(meta, "THE STORY TEXT", "standard")
        assert.truthy(p.user:find("Dune", 1, true))
        assert.truthy(p.user:find("Frank Herbert", 1, true))
        assert.truthy(p.user:find("Chapter 12", 1, true))
        assert.truthy(p.user:find("THE STORY TEXT", 1, true))
    end)

    it("instructs the model to never go beyond the provided text", function()
        local p = Prompts.build(meta, "text", "standard")
        assert.truthy(p.system:find("Never reveal", 1, true))
        assert.truthy(p.system:find("beyond the provided text", 1, true))
        assert.truthy(p.system:find("same language", 1, true))
    end)

    it("varies target length by preset", function()
        local short = Prompts.build(meta, "text", "short")
        local standard = Prompts.build(meta, "text", "standard")
        local detailed = Prompts.build(meta, "text", "detailed")
        assert.truthy(short.system:find("150", 1, true))
        assert.truthy(standard.system:find("400", 1, true))
        assert.truthy(detailed.system:find("800", 1, true))
    end)

    it("falls back to standard length for unknown presets", function()
        local p = Prompts.build(meta, "text", "gigantic")
        assert.truthy(p.system:find("400", 1, true))
    end)

    it("degrades gracefully when metadata is missing", function()
        local p = Prompts.build(nil, "just the text", "standard")
        assert.truthy(p.user:find("Text read so far", 1, true))
        assert.truthy(p.user:find("just the text", 1, true))
        assert.is_nil(p.user:find("Book:", 1, true))
    end)
end)

describe("kocatchup_prompts.build_update and build_reground", function()
    before_each(function() H.reset() end)

    local meta = { title = "Dune", authors = "Frank Herbert", chapter = "Chapter 20" }

    it("update: contains previous recap, delta, and preserve-coverage merge instruction", function()
        local p = Prompts.build_update(meta, "PREV RECAP", "DELTA TEXT", "standard")
        assert.truthy(p.user:find("PREV RECAP", 1, true))
        assert.truthy(p.user:find("DELTA TEXT", 1, true))
        assert.truthy(p.system:find("preserving the earlier events", 1, true))
        assert.truthy(p.system:find("Never reveal", 1, true))
        assert.truthy(p.system:find("same language", 1, true))
        assert.truthy(p.system:find("400", 1, true))
    end)

    it("reground: contains tail text, previous recap, and prior-context instruction", function()
        local p = Prompts.build_reground(meta, "TAIL TEXT", "PREV RECAP", "detailed")
        assert.truthy(p.user:find("TAIL TEXT", 1, true))
        assert.truthy(p.user:find("PREV RECAP", 1, true))
        assert.truthy(p.system:find("authoritative for events BEFORE", 1, true))
        assert.truthy(p.system:find("Preserve that earlier coverage", 1, true))
        assert.truthy(p.system:find("Never reveal", 1, true))
        assert.truthy(p.system:find("800", 1, true))
    end)

    it("both degrade gracefully without metadata and fall back to standard length", function()
        local u = Prompts.build_update(nil, "R", "D", "gigantic")
        assert.truthy(u.system:find("400", 1, true))
        assert.is_nil(u.user:find("Book:", 1, true))
        local g = Prompts.build_reground(nil, "T", "R", nil)
        assert.truthy(g.system:find("400", 1, true))
        assert.is_nil(g.user:find("Book:", 1, true))
    end)
end)
